-- Intentionally no secondary indexes. PostgreSQL creates indexes only for PRIMARY KEY and UNIQUE constraints below.
CREATE TABLE users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(200) NOT NULL,
  email varchar(320) NOT NULL UNIQUE,
  country varchar(100) NOT NULL,
  city varchar(100) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE categories (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name varchar(120) NOT NULL);
CREATE TABLE brands (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name varchar(160) NOT NULL);
CREATE TABLE products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name varchar(300) NOT NULL, description text NOT NULL,
  brand_id integer NOT NULL REFERENCES brands(id), category_id integer NOT NULL REFERENCES categories(id),
  price numeric(12,2) NOT NULL, stock integer NOT NULL, rating numeric(3,2) NOT NULL, created_at timestamptz NOT NULL
);
CREATE TABLE orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id bigint NOT NULL REFERENCES users(id),
  status varchar(30) NOT NULL, total_amount numeric(14,2) NOT NULL, created_at timestamptz NOT NULL
);
CREATE TABLE order_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, order_id bigint NOT NULL REFERENCES orders(id),
  product_id bigint NOT NULL REFERENCES products(id), quantity integer NOT NULL, price numeric(12,2) NOT NULL
);
CREATE TABLE reviews (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id bigint NOT NULL REFERENCES users(id),
  product_id bigint NOT NULL REFERENCES products(id), rating integer NOT NULL, comment text NOT NULL, created_at timestamptz NOT NULL
);
CREATE TABLE wishlists (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id bigint NOT NULL REFERENCES users(id), product_id bigint NOT NULL REFERENCES products(id));
